[package]
name = "vgm"
version = "0.1.0"
authors = ["Odin Dutton <odindutton@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.0.1"
custom_debug_derive = "0.2.0"
byteorder = "1.3.2"
bitflags = "1.2.1"
flate2 = "1.0"
